
# Setting up working directory
# WORKDIR /go/src/github.com/alexstoick/wow/web
# RUN ls
# RUN go install

# Setting up environment variables
ENV ENV dev

# My web app is running on port 8080 so exposed that port for the world
# EXPOSE 3000
ENTRYPOINT ["/go/bin/web"]
